name: Unit Tests (Lab05)
on:
  push:
    paths:
      - 'Lab05/AudioSystem.cpp'
jobs:
  runtest:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Build and run tests
        run: bash Scripts/tests.sh -xe
        env:
          LAB_TO_TEST: Lab05
